name: Build
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.0
          - 2.7
          - 3.0
          - 3.4
          - ruby-head
          - jruby-9.1
          - jruby-head
    name: Ruby ${{ matrix.ruby-version }} sample
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - run: bundle exec rake spec
